apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xdemo-go-gitops
  description: This is GitOps manifest for xdemo-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=xdemo-go
    backstage.io/kubernetes-id: xdemo-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xdemo-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xdemo-go
