apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: xdemo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xdemo-go 
  name: xdemo-go
spec:
  port:
    targetPort: 8080 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xdemo-go
    weight: 100 
